
services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "8181:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
    environment:
      STATS_USER: "admin"
      STATS_PASSWORD: "changeme"
    depends_on:
      - php
    networks:
      - beer_festival_network
    entrypoint: ["sh", "/entrypoint.sh"]

  php:
    image: php:8.2-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:ro
      - ./logs/:/var/log/mybeerfest:rw
    environment:
      DOMAIN: "beerfest.craftbeer.dk"
      FESTIVAL_TITLE: "Lorem Ipsum Festival 2025"
      FESTIVAL_TITLE_SHORT: "Lorem Ipsum '25"
      APP_LANGUAGE: "da"
      ENABLE_MAINSTYLE_FILTERING: true
      FESTIVAL_INFO_TEXT: "Welcome to Lorem Ipsum Festival 2025"
      ENABLE_STATISTICS_LOGGING: true
      CONTACT_EMAIL: "lorem@example.com"
    networks:
      - beer_festival_network
    command: sh -c "mkdir -p /var/log/mybeerfest && chown -R www-data:www-data /var/log/mybeerfest && php-fpm"

networks:
  beer_festival_network:
    driver: bridge
